version: "3.7"

services:
  database:
    image: mysql:5.7
    environment: 
      MYSQL_DATABASE: bookstore_db
      MYSQL_ROOT_PASSWORD: P123456p
      MYSQL_USER: sibel
      MYSQL_PASSWORD: Sibel_1
    networks:
      - soznet
  my-app:
    image: sibel/bookstore-api:latest
    restart: always
    depends_on:
      - database
    ports:
      - "80:80"
    networks:
      - soznet
networks:
  clarusnet:
    driver: bridge
